#------------------------------------------------------------------------------#
# XMidiCtrl profile for Behringer X-Touch Mini and Hot Start CL-650
#
# *NOTE* Requires out-of-the-box layer configuration of X-Touch Mini
#
# Based on work by Reflected Reality Simulations[1] and Marco Auer[2]
#
# Derivative work by Pilsner[3], 2024-01-18
#
# [1]: https://www.youtube.com/c/ReflectedRealitySimulations
# [2]: https://github.com/mauer
# [3]: https://github.com/pilsnerish
#------------------------------------------------------------------------------#
# XMidiCtrl is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# XMidiCtrl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with XMidiCtrl. If not, see <https://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------#

title      = "Hot Start CL-650 by Pilsner"
version    = "1"
sl_dataref = "CL650/pilot_seat"

[[device]]
name       = "Behringer X-Touch Mini"
port_in    = 0
port_out   = 1
mapping_in = [
  #----------------------------------------------------------------------------#
  # Layer A
  #----------------------------------------------------------------------------#
  { ch = 11, cc = 1, type = "enc", mode = "range", sl = "0", command_up = "CL650/DCP/1/baro_up", command_down = "CL650/DCP/1/baro_down" },
  { ch = 11, cc = 1, type = "enc", mode = "range", sl = "1", command_up = "CL650/ISI/baro_up", command_down = "CL650/ISI/baro_down" },
  { ch = 11, cc = 2, type = "enc", mode = "range", command_up = "CL650/FCP/crs1_up", command_down = "CL650/FCP/crs1_down" },
  { ch = 11, cc = 3, type = "enc", mode = "range", command_up = "CL650/FCP/vs_pitch_up", command_down = "CL650/FCP/vs_pitch_down" },
  { ch = 11, cc = 4, type = "enc", mode = "range", command_up = "CL650/FCP/speed_up", command_down = "CL650/FCP/speed_down" },
  { ch = 11, cc = 5, type = "enc", mode = "range", command_up = "CL650/FCP/hdg_up", command_down = "CL650/FCP/hdg_down" },
  { ch = 11, cc = 6, type = "enc", mode = "range", command_up = "CL650/FCP/alt_up", command_down = "CL650/FCP/alt_down" },
  { ch = 11, cc = 7, type = "enc", mode = "range", command_up = "CL650/FCP/crs2_up", command_down = "CL650/FCP/crs2_down" },
  { ch = 11, cc = 8, type = "enc", mode = "range", sl = "0", command_up = "CL650/ISI/baro_up", command_down = "CL650/ISI/baro_down" },
  { ch = 11, cc = 8, type = "enc", mode = "range", sl = "1", command_up = "CL650/DCP/2/baro_up", command_down = "CL650/DCP/2/baro_down" },
  { ch = 11, cc = 9, type = "sld", sl = "0", dataref = "CL650/overhead/map_lt/lh" },
  { ch = 11, cc = 9, type = "sld", sl = "1", dataref = "CL650/overhead/map_lt/rh" },

  { ch = 11, note =  0, type = "cmd", sl = "0", command = "CL650/DCP/1/baro_push" },
  { ch = 11, note =  0, type = "cmd", sl = "1", command = "CL650/ISI/std" },
  { ch = 11, note =  1, type = "cmd", command = "CL650/FCP/crs1_push" },
  # ch = 11, note =  2
  { ch = 11, note =  3, type = "cmd", command = "CL650/FCP/ias_mach" },
  { ch = 11, note =  4, type = "cmd", command = "CL650/FCP/hdg_sync" },
  { ch = 11, note =  5, type = "cmd", command = "CL650/FCP/alt_cancel" },
  { ch = 11, note =  6, type = "cmd", command = "CL650/FCP/crs2_push" },
  { ch = 11, note =  7, type = "cmd", sl = "0", command = "CL650/ISI/std" },
  { ch = 11, note =  7, type = "cmd", sl = "1", command = "CL650/DCP/2/baro_push" },
  { ch = 11, note =  8, type = "cmd", command = "CL650/glareshield/ATS" },
  { ch = 11, note =  9, type = "cmd", command = "CL650/DCP/1/nav_src" },
  { ch = 11, note = 10, type = "cmd", command = "CL650/FCP/vs_mode" },
  { ch = 11, note = 11, type = "cmd", command = "CL650/FCP/flc_mode" },
  { ch = 11, note = 12, type = "cmd", command = "CL650/FCP/hdg_mode" },
  { ch = 11, note = 13, type = "cmd", command = "CL650/FCP/alt_mode" },
  { ch = 11, note = 14, type = "cmd", command = "CL650/DCP/2/nav_src" },
  { ch = 11, note = 15, type = "cmd", command = "CL650/FCP/ap_eng" },
  { ch = 11, note = 16, type = "cmd", command = "CL650/glareshield/master_warn_L" },
  { ch = 11, note = 17, type = "cmd", command = "CL650/FCP/fd1" },
  { ch = 11, note = 18, type = "cmd", command = "CL650/FCP/vnav_mode" },
  { ch = 11, note = 19, type = "cmd", command = "CL650/FCP/appr_mode" },
  { ch = 11, note = 20, type = "cmd", command = "CL650/FCP/nav_mode" },
  { ch = 11, note = 21, type = "cmd", command = "CL650/FCP/bc_mode" },
  { ch = 11, note = 22, type = "cmd", command = "CL650/FCP/fd2" },
  { ch = 11, note = 23, type = "cmd", command = "CL650/glareshield/master_warn_R" },

  #----------------------------------------------------------------------------#
  # Layer B
  #----------------------------------------------------------------------------#
  { ch = 11, cc = 11, type = "enc", mode = "range", sl = "0", command_up = "CL650/DCP/1/menu_adv_up", command_down = "CL650/DCP/1/menu_adv_down" },
  { ch = 11, cc = 11, type = "enc", mode = "range", sl = "1", command_up = "CL650/DCP/2/menu_adv_up", command_down = "CL650/DCP/2/menu_adv_down" },
  { ch = 11, cc = 12, type = "enc", mode = "range", sl = "0", command_up = "CL650/DCP/1/menu_data_up", command_down = "CL650/DCP/1/menu_data_down" },
  { ch = 11, cc = 12, type = "enc", mode = "range", sl = "1", command_up = "CL650/DCP/2/menu_data_up", command_down = "CL650/DCP/2/menu_data_down" },
  { ch = 11, cc = 13, type = "enc", mode = "range", sl = "0", command_up = "CL650/DCP/1/tilt_up", command_down = "CL650/DCP/1/tilt_down" },
  { ch = 11, cc = 13, type = "enc", mode = "range", sl = "1", command_up = "CL650/DCP/2/tilt_up", command_down = "CL650/DCP/2/tilt_down" },
  { ch = 11, cc = 14, type = "enc", mode = "range", sl = "0", command_up = "CL650/DCP/1/range_up", command_down = "CL650/DCP/1/range_down" },
  { ch = 11, cc = 14, type = "enc", mode = "range", sl = "1", command_up = "CL650/DCP/2/range_up", command_down = "CL650/DCP/2/range_down" },
  { ch = 11, cc = 15, type = "enc", mode = "range", sl = "0", command_up = "CL650/CCP/1/menu_adv_up", command_down = "CL650/CCP/1/menu_adv_down" },
  { ch = 11, cc = 15, type = "enc", mode = "range", sl = "1", command_up = "CL650/CCP/2/menu_adv_up", command_down = "CL650/CCP/2/menu_adv_down" },
  { ch = 11, cc = 16, type = "enc", mode = "range", sl = "0", command_up = "CL650/CCP/1/menu_data_up", command_down = "CL650/CCP/1/menu_data_down" },
  { ch = 11, cc = 16, type = "enc", mode = "range", sl = "1", command_up = "CL650/CCP/2/menu_data_up", command_down = "CL650/CCP/2/menu_data_down" },
  { ch = 11, cc = 17, type = "enc", mode = "range", sl = "0", command_up = "CL650/CCP/1/radio_adv_up", command_down = "CL650/CCP/1/radio_adv_down" },
  { ch = 11, cc = 17, type = "enc", mode = "range", sl = "1", command_up = "CL650/CCP/2/radio_adv_up", command_down = "CL650/CCP/2/radio_adv_down" },
  { ch = 11, cc = 18, type = "enc", mode = "range", sl = "0", command_up = "CL650/CCP/1/radio_data_up", command_down = "CL650/CCP/1/radio_data_down" },
  { ch = 11, cc = 18, type = "enc", mode = "range", sl = "1", command_up = "CL650/CCP/2/radio_data_up", command_down = "CL650/CCP/2/radio_data_down" },

  { ch = 11, note = 24, type = "cmd", sl = "0", command = "CL650/DCP/1/menu_push" },
  { ch = 11, note = 24, type = "cmd", sl = "1", command = "CL650/DCP/2/menu_push" },
  { ch = 11, note = 25, type = "cmd", sl = "0", command = "CL650/DCP/1/menu_push" },
  { ch = 11, note = 25, type = "cmd", sl = "1", command = "CL650/DCP/2/menu_push" },
  { ch = 11, note = 26, type = "cmd", sl = "0", command = "CL650/DCP/1/tilt_auto" },
  { ch = 11, note = 26, type = "cmd", sl = "1", command = "CL650/DCP/2/tilt_auto" },
  { ch = 11, note = 27, type = "cmd", sl = "0", command = "CL650/DCP/1/tilt_auto" },
  { ch = 11, note = 27, type = "cmd", sl = "1", command = "CL650/DCP/2/tilt_auto" },
  { ch = 11, note = 28, type = "cmd", sl = "0", command = "CL650/CCP/1/menu_push" },
  { ch = 11, note = 28, type = "cmd", sl = "1", command = "CL650/CCP/2/menu_push" },
  { ch = 11, note = 29, type = "cmd", sl = "0", command = "CL650/CCP/1/menu_push" },
  { ch = 11, note = 29, type = "cmd", sl = "1", command = "CL650/CCP/2/menu_push" },
  { ch = 11, note = 30, type = "cmd", sl = "0", command = "CL650/CCP/1/radio_push" },
  { ch = 11, note = 30, type = "cmd", sl = "1", command = "CL650/CCP/2/radio_push" },
  { ch = 11, note = 31, type = "pnp", sl = "0", command_push = "CL650/CCP/1/radio_push", command_pull = "CL650/CCP/1/atc" },
  { ch = 11, note = 31, type = "pnp", sl = "1", command_push = "CL650/CCP/2/radio_push", command_pull = "CL650/CCP/2/atc" },
  { ch = 11, note = 32, type = "cmd", sl = "0", command = "CL650/DCP/1/menu" },
  { ch = 11, note = 32, type = "cmd", sl = "1", command = "CL650/DCP/2/menu" },
  { ch = 11, note = 33, type = "cmd", sl = "0", command = "CL650/DCP/1/esc" },
  { ch = 11, note = 33, type = "cmd", sl = "1", command = "CL650/DCP/2/esc" },
  { ch = 11, note = 34, type = "cmd", sl = "0", command = "CL650/DCP/1/brg_src" },
  { ch = 11, note = 34, type = "cmd", sl = "1", command = "CL650/DCP/2/brg_src" },
  { ch = 11, note = 35, type = "cmd", sl = "0", command = "CL650/DCP/1/refs" },
  { ch = 11, note = 35, type = "cmd", sl = "1", command = "CL650/DCP/2/refs" },
  { ch = 11, note = 36, type = "cmd", sl = "0", command = "CL650/CCP/1/upr_menu" },
  { ch = 11, note = 36, type = "cmd", sl = "1", command = "CL650/CCP/2/upr_menu" },
  { ch = 11, note = 37, type = "cmd", sl = "0", command = "CL650/CCP/1/esc" },
  { ch = 11, note = 37, type = "cmd", sl = "1", command = "CL650/CCP/2/esc" },
  { ch = 11, note = 38, type = "cmd", sl = "0", command = "CL650/CCP/1/chart" },
  { ch = 11, note = 38, type = "cmd", sl = "1", command = "CL650/CCP/2/chart" },
  { ch = 11, note = 39, type = "pnp", sl = "0", command_push = "CL650/CCP/1/freq", command_pull = "CL650/CCP/1/radio" },
  { ch = 11, note = 39, type = "pnp", sl = "1", command_push = "CL650/CCP/2/freq", command_pull = "CL650/CCP/2/radio" },
  { ch = 11, note = 40, type = "cmd", sl = "0", command = "CL650/DCP/1/frmt" },
  { ch = 11, note = 40, type = "cmd", sl = "1", command = "CL650/DCP/2/frmt" },
  { ch = 11, note = 41, type = "cmd", sl = "0", command = "CL650/DCP/1/tfc" },
  { ch = 11, note = 41, type = "cmd", sl = "1", command = "CL650/DCP/2/tfc" },
  { ch = 11, note = 42, type = "cmd", sl = "0", command = "CL650/DCP/1/tr_wx" },
  { ch = 11, note = 42, type = "cmd", sl = "1", command = "CL650/DCP/2/tr_wx" },
  { ch = 11, note = 43, type = "cmd", sl = "0", command = "CL650/DCP/1/rdr_menu" },
  { ch = 11, note = 43, type = "cmd", sl = "1", command = "CL650/DCP/2/rdr_menu" },
  { ch = 11, note = 44, type = "cmd", sl = "0", command = "CL650/CCP/1/lwr_menu" },
  { ch = 11, note = 44, type = "cmd", sl = "1", command = "CL650/CCP/2/lwr_menu" },
  { ch = 11, note = 45, type = "cmd", sl = "0", command = "CL650/CCP/1/mem1" },
  { ch = 11, note = 45, type = "cmd", sl = "1", command = "CL650/CCP/2/mem1" },
  { ch = 11, note = 46, type = "cmd", sl = "0", command = "CL650/CCP/1/mem2" },
  { ch = 11, note = 46, type = "cmd", sl = "1", command = "CL650/CCP/2/mem2" },
  { ch = 11, note = 47, type = "cmd", sl = "0", command = "CL650/CCP/1/mem3" },
  { ch = 11, note = 47, type = "cmd", sl = "1", command = "CL650/CCP/2/mem3" },
]
mapping_out = [
  #----------------------------------------------------------------------------#
  # Layer A
  #----------------------------------------------------------------------------#
  { ch = 11, note =  8, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/ats_L", "CL650/lamps/glareshield/ats_R" ], value_off = "0" },
  # ch = 11, note =  9
  { ch = 11, note = 10, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/vs_1", "CL650/lamps/glareshield/FCP/vs_2" ], value_off = "0" },
  { ch = 11, note = 11, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/flc_1", "CL650/lamps/glareshield/FCP/flc_2" ], value_off = "0" },
  { ch = 11, note = 12, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/hdg_1", "CL650/lamps/glareshield/FCP/hdg_2" ], value_off = "0" },
  { ch = 11, note = 13, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/alt_1", "CL650/lamps/glareshield/FCP/alt_2" ], value_off = "0" },
  # ch = 11, note = 14
  { ch = 11, note = 15, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/ap_eng_1", "CL650/lamps/glareshield/FCP/ap_eng_2" ], value_off = "0" },
  { ch = 11, note = 16, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/master_warn_L", "CL650/lamps/glareshield/master_caut_L" ], value_off = "0" },
  # ch = 11, note = 17
  { ch = 11, note = 18, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/vnav_1", "CL650/lamps/glareshield/FCP/vnav_2" ], value_off = "0" },
  { ch = 11, note = 19, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/appr_1", "CL650/lamps/glareshield/FCP/appr_2" ], value_off = "0" },
  { ch = 11, note = 20, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/nav_1", "CL650/lamps/glareshield/FCP/nav_2" ], value_off = "0" },
  { ch = 11, note = 21, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/FCP/bc_1", "CL650/lamps/glareshield/FCP/bc_2" ], value_off = "0" },
  # ch = 11, note = 22
  { ch = 11, note = 23, velocity_on = 1, type = "drf", dataref = [ "CL650/lamps/glareshield/master_warn_R", "CL650/lamps/glareshield/master_caut_R" ], value_off = "0" },
]
